const CANDY_MACHINE_CONFIG = process.env.REACT_APP_CANDY_MACHINE_CONFIG ?? ''
const CANDY_MACHINE_ID = process.env.REACT_APP_CANDY_MACHINE_ID ?? ''
const CANDY_START_DATE = process.env.REACT_APP_CANDY_START_DATE ?? ''
const SOLANA_NETWORK = process.env.REACT_APP_SOLANA_NETWORK ?? ''
const SOLANA_RPC_HOST = process.env.REACT_APP_SOLANA_RPC_HOST ?? ''

const TREASURY_ADDRESS = process.env.REACT_APP_TREASURY_ADDRESS ?? ''

const PRESALE_DURATION = process.env.REACT_APP_PRESALE_DURATION
    ? parseInt(process.env.REACT_APP_PRESALE_DURATION)
    : 300
const PRESALE_LIMIT = process.env.REACT_APP_PRESALE_LIMIT
    ? parseInt(process.env.REACT_APP_PRESALE_LIMIT)
    : 1
const PRESALE_WHITELIST = process.env.REACT_APP_PRESALE_WHITELIST
    ? process.env.REACT_APP_PRESALE_WHITELIST.split(',')
    : [
          'FZT4FtHFdDEFXmfk8eC7on1vhENr7pE7xeYGaVMdiZiz', //client
          'FLiQ37zG3rAimhQFpur1PG8LzYguX3przaPMbjRdbue9' //me
      ]

// const PRESALE_LIMIT = 1
// const PRESALE_WHITELIST = ['empty']

export {
    CANDY_MACHINE_CONFIG,
    CANDY_MACHINE_ID,
    CANDY_START_DATE,
    SOLANA_NETWORK,
    SOLANA_RPC_HOST,
    TREASURY_ADDRESS,
    PRESALE_DURATION,
    PRESALE_LIMIT,
    PRESALE_WHITELIST
}
